// Generated by scripts/fetch-blog-posts.js from https://anish-shilpakar.com.np/rss.xml
// Do not edit by hand — re-run the script to refresh (see comment there for why).
// Last generated: 2026-08-09T16:49:20.973Z

const BLOG_POSTS = [
  {
    "title": "Real-World Data Engineering: Healthcare Claims Pipeline Using AWS SNS, SQS, Snowpipe, and dbt",
    "excerpt": "Part 1 of 2: This post covers building the foundational data pipeline for a healthcare claims analytics project called claims-pulse. We walk through…",
    "href": "https://anish-shilpakar.com.np/real-world-data-engineering-healthcare-claims-pipeline-using-aws-sns-sqs-snowpipe-and-dbt",
    "date": "Dec 2025"
  },
  {
    "title": "How I Built a Production-Grade E-Commerce Data Analytics Pipeline With  AWS and Databricks",
    "excerpt": "Introduction Most data engineering tutorials hand you a clean CSV file and say, \"Here, load this into a table.\" Real life is nothing like that. In…",
    "href": "https://anish-shilpakar.com.np/how-i-built-a-production-grade-e-commerce-data-analytics-pipeline-with-aws-and-databricks",
    "date": "Nov 2025"
  },
  {
    "title": "Deploying Kubernetes on AWS EC2: Infrastructure Management Made Easy for Data Engineers",
    "excerpt": "Introduction In data engineering, efficient infrastructure management is as crucial as building robust data pipelines. As data volumes grow,…",
    "href": "https://anish-shilpakar.com.np/deploying-kubernetes-on-aws-ec2-infrastructure-management-made-easy-for-data-engineers",
    "date": "Oct 2024"
  }
];
