// Generated by scripts/generate-books-data.js from data/books.json
// Do not edit by hand — edit data/books.json (or via the CMS at /admin) and re-run.

const CURRENT_BOOKS = [
  {
    "title": "The Catcher in the Rye",
    "author": "J.D. Salinger",
    "slotId": "book-current"
  }
];

const PAST_BOOKS = [
  {
    "title": "Frankenstein",
    "author": "Mary Shelley",
    "slotId": "book-past-1"
  },
  {
    "title": "Tuesdays with Morrie",
    "author": "Mitch Albom",
    "slotId": "book-past-2"
  },
  {
    "title": "The Stranger",
    "author": "Albert Camus",
    "slotId": "book-past-3"
  },
  {
    "title": "Crime and Punishment",
    "author": "Fyodor Dostoevsky",
    "slotId": "book-past-4"
  },
  {
    "title": "The Metamorphosis",
    "author": "Franz Kafka",
    "slotId": "book-past-5"
  }
];
