// Template for js/config.js — copy is generated by scripts/generate-config.js from .env.
const EMAILJS_CONFIG = {
  serviceId: 'your_service_id',
  templateId: 'your_template_id',
  publicKey: 'your_public_key',
};
