// Generated by scripts/fetch-pinterest-photos.js from https://www.pinterest.com/anishshilpakar/daily-snaps.rss
// Do not edit by hand — re-run the script to refresh (see comment there for why).
// Last generated: 2026-09-21T02:42:33.682Z

const PINTEREST_PHOTOS = [
  {
    "src": "https://i.pinimg.com/236x/ff/87/97/ff8797e51f7ef8f79f32bf1dd21a8aee.jpg",
    "href": "https://www.pinterest.com/pin/849773023482705898/"
  },
  {
    "src": "https://i.pinimg.com/236x/0f/11/c3/0f11c3c833acaae6b921526f22280160.jpg",
    "href": "https://www.pinterest.com/pin/849773023482845768/"
  },
  {
    "src": "https://i.pinimg.com/236x/06/c0/c6/06c0c62c594fa3cda6cf7423038af639.jpg",
    "href": "https://www.pinterest.com/pin/849773023482996911/"
  },
  {
    "src": "https://i.pinimg.com/236x/4f/56/8c/4f568c2367968c34f5428fd136e1e929.jpg",
    "href": "https://www.pinterest.com/pin/849773023485357015/"
  },
  {
    "src": "https://i.pinimg.com/236x/bc/f4/99/bcf4990279fe2807fcec98090c7d2448.jpg",
    "href": "https://www.pinterest.com/pin/849773023484889544/"
  },
  {
    "src": "https://i.pinimg.com/236x/64/9f/fd/649ffdfac8d08fda8a397f2c8edd294e.jpg",
    "href": "https://www.pinterest.com/pin/849773023485116286/"
  },
  {
    "src": "https://i.pinimg.com/236x/d9/4b/38/d94b38fc196f2b40f1a952c7f9b0c56b.jpg",
    "href": "https://www.pinterest.com/pin/849773023484955492/"
  },
  {
    "src": "https://i.pinimg.com/236x/8b/bc/20/8bbc201f6dcffe80bae960b9da5c288a.jpg",
    "href": "https://www.pinterest.com/pin/849773023486043436/"
  },
  {
    "src": "https://i.pinimg.com/236x/d0/29/a7/d029a74aafcd39adcbe0d5d9abf33848.jpg",
    "href": "https://www.pinterest.com/pin/849773023486043427/"
  },
  {
    "src": "https://i.pinimg.com/236x/94/cd/5a/94cd5a0b059ea6087f40661af1272dca.jpg",
    "href": "https://www.pinterest.com/pin/849773023486043423/"
  }
];
