// Generated by scripts/fetch-pinterest-photos.js from https://www.pinterest.com/anishshilpakar/daily-snaps.rss
// Do not edit by hand — re-run the script to refresh (see comment there for why).
// Last generated: 2026-10-09T22:05:17.406Z

const PINTEREST_PHOTOS = [
  {
    "src": "https://i.pinimg.com/236x/ff/87/97/ff8797e51f7ef8f79f32bf1dd21a8aee.jpg",
    "href": "https://www.pinterest.com/pin/849773023482705898/"
  },
  {
    "src": "https://i.pinimg.com/236x/0f/11/c3/0f11c3c833acaae6b921526f22280160.jpg",
    "href": "https://www.pinterest.com/pin/849773023482845768/"
  },
  {
    "src": "https://i.pinimg.com/236x/4f/56/8c/4f568c2367968c34f5428fd136e1e929.jpg",
    "href": "https://www.pinterest.com/pin/849773023485357015/"
  },
  {
    "src": "https://i.pinimg.com/236x/06/c0/c6/06c0c62c594fa3cda6cf7423038af639.jpg",
    "href": "https://www.pinterest.com/pin/849773023482996911/"
  },
  {
    "src": "https://i.pinimg.com/236x/01/65/ee/0165ee00c33098bee80df45783828ef6.jpg",
    "href": "https://www.pinterest.com/pin/849773023485357017/"
  },
  {
    "src": "https://i.pinimg.com/236x/d9/4b/38/d94b38fc196f2b40f1a952c7f9b0c56b.jpg",
    "href": "https://www.pinterest.com/pin/849773023484955492/"
  },
  {
    "src": "https://i.pinimg.com/236x/1a/79/f1/1a79f18701ed8f2754832b21e7e4ea61.jpg",
    "href": "https://www.pinterest.com/pin/849773023484908299/"
  },
  {
    "src": "https://i.pinimg.com/236x/cf/cf/46/cfcf469e69efea922c89b161bdd060ca.jpg",
    "href": "https://www.pinterest.com/pin/849773023482750515/"
  },
  {
    "src": "https://i.pinimg.com/236x/a8/54/16/a8541604093de768a0094a98e66ffcb4.jpg",
    "href": "https://www.pinterest.com/pin/849773023486206952/"
  },
  {
    "src": "https://i.pinimg.com/236x/d0/29/a7/d029a74aafcd39adcbe0d5d9abf33848.jpg",
    "href": "https://www.pinterest.com/pin/849773023486043427/"
  }
];
