// Reads .env and writes js/config.js — the values EmailJS needs in the browser.
//
// Why a generated file instead of reading .env at runtime:
// This is a plain static site with no bundler, and browsers cannot read
// .env files. js/config.js is the committed-code-safe stand-in: it's
// gitignored (like .env) and regenerated from .env before serving/deploying.
//
// Run this after editing .env:
//   node scripts/generate-config.js

const fs = require('fs');
const path = require('path');

const ENV_PATH = path.join(__dirname, '..', '.env');
const OUTPUT_PATH = path.join(__dirname, '..', 'js', 'config.js');

function parseEnv(contents) {
  const env = {};
  for (const line of contents.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    env[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return env;
}

if (!fs.existsSync(ENV_PATH)) {
  console.error('.env not found — copy it from the values in your EmailJS dashboard.');
  process.exit(1);
}

const env = parseEnv(fs.readFileSync(ENV_PATH, 'utf8'));

const output = `// Generated by scripts/generate-config.js from .env — do not edit by hand, do not commit.
const EMAILJS_CONFIG = {
  serviceId: '${env.EMAILJS_SERVICE_ID || ''}',
  templateId: '${env.EMAILJS_TEMPLATE_ID || ''}',
  publicKey: '${env.EMAILJS_PUBLIC_KEY || ''}',
};
`;

fs.writeFileSync(OUTPUT_PATH, output);
console.log(`Wrote ${OUTPUT_PATH}`);
